layout_spectrum: 1
typography_spectrum: 0.9455569
color:
  lightness: 1
  brandStrength: 0.4930886
  saturation: 1
  rhythmicContrast: 0.9418023
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Themixxmasters
